CREATE TABLE IF NOT EXISTS STUDENT (
    NAME TEXT,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER);

INSERT INTO STUDENT (NAME, ADDRESS, PHONE, AGE) VALUES
('RAM','DELHI','1',18),
('RAMESH','GURGAON','2',18),
('SUJIT','ROHTAK','3',20),
('SURESH','DELHI','4',18),
('AMAN','ROHTAK','5',20),
('HARSH','GURGAON','6',18);

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE AGE=18 AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE AGE=18 AND ADRESS='RAM';

SELECT * FROM STUDENT WHERE NAME='RAM' OR NAME = 'SUJIT';

SELECT * FROM STUDENT WHERE NAME='RAM' OR AGE = 20;

SELECT * FROM STUDENT WHERE AGE=18 AND (NAME='RAM' OR NAME='RAMESH');