CREATE TABLE IF NOT EXISTS EXPERIMENTS (
YEAR INTEGER,
SCIENTIST TEXT,
COUNTRY TEXT,
RESULT TEXT
);

INSERT INTO EXPERIMENTS (YEAR,SCIENTIST,COUNTRY,RESULT) VALUES
(1970,'ALEXA','GERMANY','SUCESS'),
(1970,'RYAN','FRANCE','FAIL'),
(1971,'PAUL','UKRAINE','FAIL'),
(1971,'PENELOPE','GREECE','SUCCESS'),
(1972,'JULIET','HUNGSRY','FAIL'),
(1972,'LLOYD','RUSSIA','SUCCESS'),
(1973,'NYA','SWEDEN','FAIL'),
(1980,'ROMEO','AUSTRIA','SUCCESS'),
(1981,'HAMILTON','HUNGARY','SUCCESS'),
(1975,'KAI','NORWAY','FAIL');

SELECT *
FROM EXPERIMENTS
WHERE SCIENTIST NOT LIKE 'P%'; 