CREATE TABLE IF NOT EXISTS CUSTOMER(
CUSTOMER_ID TEXT PRIMARY KEY,
CUSTOMER_NAME TEXT,
CITY TEXT,
GRADE TEXT
);

INSERT INTO CUSTOMER(CUSTOMER_ID,CUSTOMER_NAME,CITY,GRADE)
VALUES
('0001', 'ALICE', 'PHILADELPHIA', '98'),
('0002', 'EVAN', 'CALIFORNIA', '124'),
('0003', 'PENELOPE', 'NEW YORK', '87'),
('0004', 'ETHAN', 'CHICAGO', '132'),
('0005', 'KAI', 'NEW YORK', '143');

SELECT * FROM CUSTOMER WHERE CITY='NEW YORK' AND GRADE > 100; 
SELECT * FROM CUSTOMER WHERE CITY='NEW YORK' OR GRADE > 100; 