CREATE TABLE IF NOT EXISTS GRADES(
ID TEXT,
STUDENT_NAME TEXT,
GENDER TEXT,
GRADE INTEGER);

INSERT INTO GRADES (ID, STUDENT_NAME, GENDER, GRADE) VALUES
('0201','EVA','F', 86),
('0402','NYA','F', 99),
('3009','JEFF','M', 92),
('1405','ANNA','F', 87),
('0777','LLOYD','M', 95);

SELECT AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS;
