CREATE TABLE Students(
STUDENT_ID INTEGER PRIMARY KEY,
NAME TEXT,
AGE INTEGER,
GRADE TEXT,
CITY TEXT);

INSERT INTO Students(STUDENT_ID,NAME,AGE,GRADE,CITY)
VALUES
(1,'AARAV',14,'8TH','MUMBAI'),
(2,'DIYA',13,'7TH','CHENNAI'),
(3,'ROHAN',15,'9TH','DELHI'),
(4,'ANANYA',14,'8TH','BENGALORE'),
(5,'KIRAN',13,'7TH','HYDERABAD');
SELECT * FROM Students;
SELECT * FROM Students WHERE GRADE='8TH' ORDER BY AGE;
UPDATE Students SET CITY ='PUNE' WHERE STUDENT_ID=1;
DELETE FROM Students WHERE STUDENT_ID=5;
SELECT*FROM Students;
